theme: jekyll-theme-cayman
title: Gemstone.Web
description: GPA Gemstone Web Library
github:
  repository_name: gemstone/web
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji
